#Local MongoDB config
spring:
  data:
    mongodb-uri: mongodb://localhost:27017/local
    mongodb:
     database: local
  application:
    name: products
  cloud:
    config:
      import-check:
        enabled: false
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
#  config:
#    import : config-server:http://localhost:8100/config-server

# App config
server:
  port: 8103


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



